HOST = "localhost"
DB = "Lofty_Redfin"
USER = "root"
PASSWD = "Password@1"

#Items to be left out
USELESS_DATA_POINTS = ["FAVORITE", "INTERESTED", "NEXT_OPEN_HOUSE_START_TIME", "NEXT_OPEN_HOUSE_END_TIME", "STATUS", "SALE_TYPE"]

HEADERS = ["SALE_TYPE", "SOLD_DATE", "PROPERTY_TYPE", "ADDRESS", "CITY", "STATE", "ZIP", "PRICE", "BEDS", "BATHS", "LOCATION", "SQUARE_FEET", 
        "LOT_SIZE", "YEAR_BUILT", "DAYS_ON_MARKET", "PRICE_PER_SQUARE_FEET", "HOA_MONTH", "STATUS", "NEXT_OPEN_HOUSE_START_TIME", "NEXT_OPEN_HOUSE_END_TIME", 
        "URL", "SOURCE", "MLS", "FAVORITE", "INTERESTED", "LATITUDE", "LONGITUDE"]

HOUSE_FIELDS = [ "SOLD_DATE", "PROPERTY_TYPE", "ADDRESS", "CITY", "STATE", "ZIP", "PRICE", "BEDS", "BATHS", "LOCATION", "SQUARE_FEET", 
        "LOT_SIZE", "YEAR_BUILT", "DAYS_ON_MARKET", "HOA_MONTH", "URL", "SOURCE", "MLS", "LATITUDE", "LONGITUDE",
        "ADDRESS", "LOCATION", "CITY", "ZIP", "STATE"]

ADDRESS_FIELDS = ["ADDRESS", "LOCATION", "CITY", "ZIP", "STATE"]
